In [1]:
import numpy as np

In [3]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [5]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [6]:
matrix**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [9]:
np.mean(matrix, axis=1)

array([2., 5., 8.])

In [10]:
matrix.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [12]:
matrix.trace()

15

In [18]:
np.dot(matrix, matrix)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [19]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])